on:
  push:
    paths:
      - "config/**"
  pull_request:
    paths:
      - "config/**"
  workflow_dispatch:

jobs:
  build:
    uses: ClicketySplit/zmk/.github/workflows/build-user-config.yml@clickety_split_series_zmk_v3.5_power_domains
